#ifndef HEADER_H
# define HEADER_H
# include <stdio.h> //printf, scanf, ...
# include <string.h> //memcpy, strlen, ...
# include <unistd.h> //fork, write, sleep...
# include <stdlib.h> //malloc, free, exit...
# define ABS(x) (x < 0) ? (-x) : (x)


double probaDistance(double dist, int *locations, int n);


#endif
